#!/usr/bin/env python3
"""mirror_extra_canonical_for_cdn.py

Mirror chapter-level extra-canonical YAMLs into the nested verse-level
layout the deployed Bible publisher Lambda expects.

The deployed Bible publisher Lambda matches
paths like ``translation/<section>/<bookSlug>/<NNN>/<NNN>.yaml`` —
per-verse nested structure. Our Didache / 1 Clement drafters emit
chapter-level YAMLs at ``translation/extra_canonical/<slug>/<NNN>.yaml``
(single file per chapter, continuous-prose translation inside).

These texts are not verse-subdivided in standard reading editions,
so we emit each chapter as a single synthetic verse-1 YAML that the
Lambda will pick up. The mirror files are regenerated from the
authoritative flat files whenever this script is run; flat files
remain the system of record for drafting and review.

Usage:
  python3 tools/mirror_extra_canonical_for_cdn.py

Regenerates mirrors for all configured books. Safe to re-run.
"""
from __future__ import annotations

import pathlib
import sys

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
TRANSLATION_ROOT = REPO_ROOT / "translation" / "extra_canonical"

# Books with chapter-level YAMLs that need mirroring for the CDN Lambda.
# Each tuple: (flat-dir-slug, reference-display-name, chapter-range)
# chapter_range is inclusive.
MIRROR_TARGETS: list[tuple[str, str, int]] = [
    ("didache", "Didache", 16),
    ("1_clement", "1 Clement", 65),
    # 2 Baruch used to be mirrored as synthetic verse-1 chapter blocks, but
    # it now has real reader-facing verse YAMLs under 2_baruch/NNN/VVV.yaml.
    # Do not mirror it here, or publishing will collapse multi-verse chapters.
]


def mirror_one(slug: str, display: str, max_chapter: int) -> tuple[int, int]:
    """Mirror a book's flat chapter YAMLs into nested verse-level.

    Returns (chapters_mirrored, chapters_skipped).
    """
    book_dir = TRANSLATION_ROOT / slug
    if not book_dir.exists():
        return (0, 0)
    mirrored = skipped = 0
    for chapter in range(1, max_chapter + 1):
        flat_path = book_dir / f"{chapter:03d}.yaml"
        if not flat_path.exists():
            skipped += 1
            continue
        record = yaml.safe_load(flat_path.read_text(encoding="utf-8")) or {}
        text = str(((record.get("translation") or {}).get("text", "")) or "").strip()
        if not text:
            skipped += 1
            continue
        # The nested mirror carries the full chapter translation as a
        # synthetic "verse 1" so the Lambda's per-verse regex matches.
        # The reference string follows the canonical "Book N:V" shape
        # the Lambda uses to attribute verses to books.
        mirror_record = {
            "id": f"{record.get('id', '').split('.')[0] or slug.upper()}.{chapter}.1",
            "reference": f"{display} {chapter}:1",
            "unit": "verse",
            "book": display,
            "source": record.get("source", {}),
            "translation": {
                "text": text,
                "philosophy": (record.get("translation") or {}).get("philosophy"),
            },
            "note": (
                "Synthetic single-verse mirror of the chapter-level "
                "authoritative YAML. Generated by "
                "tools/mirror_extra_canonical_for_cdn.py so the "
                "Bible publisher Lambda (which expects nested verse-level "
                "paths) picks up this book. Drafting and review both "
                "operate on the flat chapter-level file at "
                f"translation/extra_canonical/{slug}/{chapter:03d}.yaml."
            ),
        }
        # Preserve key provenance fields for auditability
        for key in ("ai_draft", "review_passes", "lexical_decisions",
                    "theological_decisions", "footnotes"):
            if key in record:
                mirror_record[key] = record[key]

        nested_dir = book_dir / f"{chapter:03d}"
        nested_dir.mkdir(exist_ok=True)
        nested_path = nested_dir / "001.yaml"
        nested_path.write_text(
            yaml.safe_dump(mirror_record, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
        mirrored += 1
    return (mirrored, skipped)


def main() -> int:
    total_mirrored = total_skipped = 0
    for slug, display, max_chapter in MIRROR_TARGETS:
        mirrored, skipped = mirror_one(slug, display, max_chapter)
        print(f"  {display:15} ({slug:10}): {mirrored} chapters mirrored, {skipped} skipped")
        total_mirrored += mirrored
        total_skipped += skipped
    print(f"\nTotal: {total_mirrored} mirrored, {total_skipped} skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
